Documentation:
  Enabled: false
Rails:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Rails/HasManyOrHasOneDependent:
  Enabled: false
TrailingBlankLines:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.3
  Include:
    - 'app/**/*'
    - '**/Rakefile'
    - '**/Gemfile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
  UseCache: false
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'feature', 'scenario', 'let']